//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
