//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Packages()
        {
            this.Orders = new HashSet<Orders>();
            this.RecipeDrugs = new HashSet<RecipeDrugs>();
        }
    
        public int ID { get; set; }
        public decimal Price { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public string Address_ZipCode { get; set; }
        public string Address_HouseNumber { get; set; }
        public string Address_ApartmentNumber { get; set; }
        public Nullable<System.DateTime> AssemblyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeDrugs> RecipeDrugs { get; set; }
    }
}
