//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeDrugs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecipeDrugs()
        {
            this.Ingridients = new HashSet<Ingridients>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MadeByID { get; set; }
        public Nullable<System.DateTime> EvaluatedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int PackageID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingridients> Ingridients { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Packages Packages { get; set; }
    }
}
